# Use root/example as user/password credentials
version: '3.2'

services:
  mongo:
    image: mongo:4.4.19
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: realworld
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      TOKEN_KEY: hello
      DATABASE_URI: "# Use root/example as user/password credentials
"
      DATABASE_USER: root
      DATABASE_PASSWORD: example
      PORT: 3000
