# Use root/example as user/password credentials
version: '3.2'

services:
  mongodb:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: realworld
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      TOKEN_KEY: hello
      DATABASE_URI: mongodb://localhost:27017/realworld
      PORT: 3000
